export const selectData = 
[
    {
        name: '区域',
        firstId: 0,
        secondData: [
            {
                name: '东城区',
                thirdData: [
                    { name: '安定门',thirdId: 0 },
                    { name: '安贞',thirdId: 1 },
                    { name: '朝阳门外',thirdId: 2 },
                    { name: '朝阳门内',thirdId: 3 },
                    { name: '崇文门',thirdId: 4 },
                    { name: '东单',thirdId: 5 },
                    { name: '东直门',thirdId: 6 },
                    { name: '地安门',thirdId: 7 },
                    { name: '东花市',thirdId: 8 },
                    { name: '东四',thirdId: 9 },
                    { name: '灯市口',thirdId: 10 },
                    { name: '广渠门',thirdId: 11 },
                    { name: '工体',thirdId: 12 },
                    { name: '和平里',thirdId: 13 },
                    { name: '交道口',thirdId: 14 },
                    { name: '建国门外',thirdId: 15 },
                    { name: '建国门内',thirdId: 16 },
                    { name: '金宝街',thirdId: 17 },
                    { name: '六铺炕',thirdId: 18 },
                    { name: '蒲黄榆',thirdId: 19 },
                    { name: '前门',thirdId: 20 },
                    { name: '陶然亭',thirdId: 21 },
                    { name: '天坛',thirdId: 22 },
                    { name: '西罗园',thirdId: 23 },
                    { name: '西单',thirdId: 24 },
                    { name: '永定门',thirdId: 25 },
                    { name: '左安门',thirdId: 26 }
                ]
            },
            { 
                name: '西城区',
                thirdData: [
                    { name: '白云路',thirdId: 27 },
                    { name: '白纸坊',thirdId: 28 },
                    { name: '菜市口',thirdId: 29 },
                    { name: '长椿街',thirdId: 30  },
                    { name: '车公庄',thirdId: 31 },
                    { name: '德胜门',thirdId: 32 },
                    { name: '阜成门',thirdId: 33 },
                    { name: '复兴门',thirdId: 34 },
                    { name: '广安门',thirdId: 35 },
                    { name: '广安门外',thirdId: 36 },
                    { name: '官园',thirdId: 37 },
                    { name: '鼓楼大街',thirdId: 38 },
                    { name: '虎坊桥',thirdId: 39 },
                    { name: '金融街',thirdId: 40 },
                    { name: '积水潭',thirdId: 41 },
                    { name: '马甸',thirdId: 42 },
                    { name: '马连道',thirdId: 43 },
                    { name: '木樨地',thirdId: 44 },
                    { name: '南礼士路',thirdId: 45 },
                    { name: '牛街',thirdId: 46 },
                    { name: '三里河',thirdId: 47 },
                    { name: '什刹海',thirdId: 48 },
                    { name: '陶然亭',thirdId: 49 },
                    { name: '天宁寺',thirdId: 50 },
                    { name: '先农坛',thirdId: 51 },
                    { name: '西便门',thirdId: 52 },
                    { name: '西单',thirdId: 53 },
                    { name: '新街口',thirdId: 54 },
                    { name: '西直门',thirdId: 55 },
                    { name: '西直门内',thirdId: 56 },
                    { name: '西直门外',thirdId: 57 },
                    { name: '宣武门',thirdId: 58 },
                    { name: '右安门内',thirdId: 59 },
                    { name: '月坛',thirdId: 60 },
                    { name: '展览路',thirdId: 61 },
                    { name: '真武庙',thirdId: 62 },
                ]
            },
            {
                name: '朝阳区',
                thirdData: [ 
                    { name: '安定门', thirdId: 63 },
                    { name: '安贞', thirdId: 64 },
                    { name: '奥林匹克公园', thirdId: 65 },
                    { name: '北苑', thirdId: 66 },
                    { name: '北工大', thirdId: 67 },
                    { name: '百子湾', thirdId: 68 },
                    { name: '成寿寺', thirdId: 69 },
                    { name: '常营', thirdId: 70 },
                    { name: '朝阳门外', thirdId: 71 },
                    { name: 'CBD', thirdId: 72 },
                    { name: '朝青', thirdId: 73 },
                    { name: '朝阳公园', thirdId: 74 },
                    { name: '东直门', thirdId: 75 },
                    { name: '东坝', thirdId: 76 },
                    { name: '大望路', thirdId: 77 },
                    { name: '东大桥', thirdId: 78 },
                    { name: '大山子', thirdId: 79 },
                    { name: '豆各庄', thirdId: 80 },
                    { name: '定福庄', thirdId: 81 },
                    { name: '方庄', thirdId: 82 },
                    { name: '垡头', thirdId: 83 },
                    { name: '广渠门', thirdId: 84 },
                    { name: '工体', thirdId: 85 },
                    { name: '高碑店', thirdId: 86 },
                    { name: '国展', thirdId: 87 },
                    { name: '甘露园', thirdId: 88 },
                    { name: '管庄', thirdId: 89 },
                    { name: '和平里', thirdId: 90 },
                    { name: '欢乐谷', thirdId: 91 },
                    { name: '惠新西街', thirdId: 92 },
                    { name: '红庙', thirdId: 93 },
                    { name: '华威桥', thirdId: 94 },
                    { name: '健翔桥', thirdId: 95 },
                    { name: '酒仙桥', thirdId: 96 },
                    { name: '劲松', thirdId: 97 },
                    { name: '建国门外', thirdId: 98 },
                    { name: '立水桥', thirdId: 99 },
                    { name: '马甸', thirdId: 100 },
                    { name: '农展馆', thirdId: 101 },
                    { name: '南沙滩', thirdId: 102 },
                    { name: '潘家园', thirdId: 103 },
                    { name: '三元桥', thirdId: 104 },
                    { name: '芍药居', thirdId: 105 },
                    { name: '石佛营', thirdId: 106 },
                    { name: '十里堡', thirdId: 107 },
                    { name: '首都机场', thirdId: 108 },
                    { name: '双井', thirdId: 109 },
                    { name: '十里河', thirdId: 110 },
                    { name: '十八里店', thirdId: 111 },
                    { name: '双桥', thirdId: 112 },
                    { name: '三里屯', thirdId: 113 },
                    { name: '四惠', thirdId: 114 },
                    { name: '通州', thirdId: 115 },
                    { name: '北苑', thirdId: 116 },
                    { name: '团结湖', thirdId: 117 },
                    { name: '太阳宫', thirdId: 118 },
                    { name: '甜水园', thirdId: 119 },
                    { name: '望京', thirdId: 120 },
                    { name: '西坝河', thirdId: 121 },
                    { name: '亚运村', thirdId: 122 },
                    { name: '亚运村小营', thirdId: 123 },
                    { name: '燕莎', thirdId: 124 },
                    { name: '中央别墅区', thirdId: 125 },
                    { name: '朝阳其它', thirdId: 126 } 
                ]
            },
            {
                name: '海淀区',
                thirdData: [ { name: '安宁庄', thirdId: 127 },
                { name: '白石桥', thirdId: 128 },
                { name: '北太平庄', thirdId: 129 },
                { name: '厂洼', thirdId: 130 },
                { name: '车道沟', thirdId: 131 },
                { name: '大钟寺', thirdId: 132 },
                { name: '定慧寺', thirdId: 133 },
                { name: '二里庄', thirdId: 134 },
                { name: '甘家口', thirdId: 135 },
                { name: '公主坟', thirdId: 136 },
                { name: '航天桥', thirdId: 137 },
                { name: '花园桥', thirdId: 138 },
                { name: '蓟门桥', thirdId: 139 },
                { name: '积水潭', thirdId: 140 },
                { name: '军博', thirdId: 141 },
                { name: '马连洼', thirdId: 142 },
                { name: '牡丹园', thirdId: 143 },
                { name: '清河', thirdId: 144 },
                { name: '上地', thirdId: 145 },
                { name: '上庄', thirdId: 146 },
                { name: '世纪城', thirdId: 147 },
                { name: '双榆树', thirdId: 148 },
                { name: '四季青', thirdId: 149 },
                { name: '苏州桥', thirdId: 150 },
                { name: '田村', thirdId: 151 },
                { name: '万柳', thirdId: 152 },
                { name: '万泉河', thirdId: 153 },
                { name: '万寿寺', thirdId: 154 },
                { name: '魏公村', thirdId: 155 },
                { name: '温泉', thirdId: 156 },
                { name: '五道口', thirdId: 157 },
                { name: '五棵松', thirdId: 158 },
                { name: '香山', thirdId: 159 },
                { name: '小西天', thirdId: 160 },
                { name: '西北旺', thirdId: 161 },
                { name: '西二旗', thirdId: 162 },
                { name: '西客站', thirdId: 163 },
                { name: '西三旗', thirdId: 164 },
                { name: '西山别墅', thirdId: 165 },
                { name: '学院路', thirdId: 166 },
                { name: '颐和园', thirdId: 167 },
                { name: '颐和园北', thirdId: 168 },
                { name: '永定路', thirdId: 169 },
                { name: '圆明园', thirdId: 170 },
                { name: '玉泉路', thirdId: 171 },
                { name: '玉渊潭', thirdId: 172 },
                { name: '皂君庙', thirdId: 173 },
                { name: '展览路', thirdId: 174 },
                { name: '知春路', thirdId: 175 },
                { name: '中关村', thirdId: 176 },
                { name: '紫竹桥', thirdId: 177 },
                { name: '紫竹院', thirdId: 178 } ]
            },
            {
                name: '昌平区',
                thirdData: [ { name: '八达岭别墅区', thirdId: 179 },
                { name: '八达岭高速', thirdId: 180 },
                { name: '百善镇', thirdId: 181 },
                { name: '北七家', thirdId: 182 },
                { name: '昌平城区', thirdId: 183 },
                { name: '大学城', thirdId: 184 },
                { name: '东小口', thirdId: 185 },
                { name: '回龙观', thirdId: 186 },
                { name: '霍营', thirdId: 187 },
                { name: '立水桥', thirdId: 188 },
                { name: '龙泽', thirdId: 189 },
                { name: '南口', thirdId: 190 },
                { name: '沙河', thirdId: 191 },
                { name: '天通西苑', thirdId: 192 },
                { name: '天通苑', thirdId: 193 },
                { name: '小汤山', thirdId: 194 },
                { name: '新城区', thirdId: 195 },
                { name: '兴寿', thirdId: 196 },
                { name: '亚北', thirdId: 197 },
                { name: '阳坊', thirdId: 198 } ]
            },
            {
                name: '大兴区',
                thirdData: [ { name: '城南别墅区', thirdId: 199 },
                { name: '大广高速', thirdId: 200 },
                { name: '第二机场住宅区', thirdId: 201 },
                { name: '黄村', thirdId: 202 },
                { name: '旧宫', thirdId: 203 },
                { name: '生物医药基地', thirdId: 204 },
                { name: '天宫院', thirdId: 205 },
                { name: '西红门', thirdId: 206 },
                { name: '亦庄', thirdId: 207 },
                { name: '亦庄新城', thirdId: 208 } ]
            },
            {
                name: '丰台区',
                thirdData: [ { name: '北大地', thirdId: 209 },
                { name: '北京西站', thirdId: 210 },
                { name: '菜户营', thirdId: 211 },
                { name: '草桥', thirdId: 212 },
                { name: '长辛店', thirdId: 213 },
                { name: '成寿寺', thirdId: 214 },
                { name: '大红门', thirdId: 215 },
                { name: '东大街', thirdId: 216 },
                { name: '东高地', thirdId: 217 },
                { name: '方庄', thirdId: 218 },
                { name: '丰台体育馆', thirdId: 219 },
                { name: '丰益桥', thirdId: 220 },
                { name: '光彩路', thirdId: 221 },
                { name: '郭公庄', thirdId: 222 },
                { name: '和义', thirdId: 223 },
                { name: '花乡', thirdId: 224 },
                { name: '角门', thirdId: 225 },
                { name: '嘉园', thirdId: 226 },
                { name: '京石高速', thirdId: 227 },
                { name: '开阳里', thirdId: 228 },
                { name: '看丹桥', thirdId: 229 },
                { name: '科丰桥', thirdId: 230 },
                { name: '科技园', thirdId: 231 },
                { name: '科学城', thirdId: 232 },
                { name: '刘家窑', thirdId: 233 },
                { name: '六里桥', thirdId: 234 },
                { name: '丽泽桥', thirdId: 235 },
                { name: '卢沟桥', thirdId: 236 },
                { name: '马家堡', thirdId: 237 },
                { name: '木樨园', thirdId: 238 },
                { name: '南苑', thirdId: 239 },
                { name: '蒲黄榆', thirdId: 240 },
                { name: '七里庄', thirdId: 241 },
                { name: '青塔', thirdId: 242 },
                { name: '世界公园', thirdId: 243 },
                { name: '宋家庄', thirdId: 244 },
                { name: '太平桥', thirdId: 245 },
                { name: '王佐', thirdId: 246 },
                { name: '小屯', thirdId: 247 },
                { name: '西罗园', thirdId: 248 },
                { name: '新发地', thirdId: 249 },
                { name: '洋桥', thirdId: 250 },
                { name: '右安门', thirdId: 251 },
                { name: '右安门外', thirdId: 252 },
                { name: '园博板块', thirdId: 253 },
                { name: '岳各庄', thirdId: 254 },
                { name: '云岗', thirdId: 255 },
                { name: '玉泉营', thirdId: 256 },
                { name: '赵公口', thirdId: 257 },
                { name: '总部基地', thirdId: 258 },
                { name: '左安门', thirdId: 259 } ]
            },
            {
                name: '石景山区',
                thirdData: [ { name: '八宝山', thirdId: 260 },
                { name: '八大处', thirdId: 261 },
                { name: '八角', thirdId: 262 },
                { name: 'CRD', thirdId: 263 },
                { name: '高井', thirdId: 264 },
                { name: '古城', thirdId: 265 },
                { name: '金顶街', thirdId: 266 },
                { name: '老山', thirdId: 267 },
                { name: '鲁谷', thirdId: 268 },
                { name: '苹果园', thirdId: 269 },
                { name: '五里坨', thirdId: 270 },
                { name: '杨庄', thirdId: 271 } ]
            },
            {
                name: '顺义区',
                thirdData: [ { name: '潮白河别墅区', thirdId: 272 },
                { name: '后沙峪', thirdId: 273 },
                { name: '京顺高速路', thirdId: 274 },
                { name: '空港工业区', thirdId: 275 },
                { name: '李桥', thirdId: 276 },
                { name: '马坡', thirdId: 277 },
                { name: '南法信', thirdId: 278 },
                { name: '首都机场', thirdId: 279 },
                { name: '顺义城', thirdId: 280 },
                { name: '顺义老城区', thirdId: 281 },
                { name: '顺义中央别墅区', thirdId: 282 },
                { name: '天竺', thirdId: 283 },
                { name: '温榆河', thirdId: 284 },
                { name: '温榆河别墅区', thirdId: 285 },
                { name: '杨镇', thirdId: 286 },
                { name: '赵全营', thirdId: 287 } ]
            },
            {
                name: '通州区',
                thirdData: [ { name: '八里桥', thirdId: 288 },
                { name: '北关', thirdId: 289 },
                { name: '次渠', thirdId: 290 },
                { name: '东关', thirdId: 291 },
                { name: '果园', thirdId: 292 },
                { name: '九棵树', thirdId: 293 },
                { name: '老城区', thirdId: 294 },
                { name: '临河里', thirdId: 295 },
                { name: '梨园', thirdId: 296 },
                { name: '潞苑南大街', thirdId: 297 },
                { name: '马驹桥', thirdId: 298 },
                { name: '乔庄', thirdId: 299 },
                { name: '商务园区', thirdId: 300 },
                { name: '台湖', thirdId: 301 },
                { name: '通州北苑', thirdId: 302 },
                { name: '通州城', thirdId: 303 },
                { name: '通州南', thirdId: 304 },
                { name: '通州其他', thirdId: 305 },
                { name: '土桥', thirdId: 306 },
                { name: '武夷花园', thirdId: 307 },
                { name: '西马庄', thirdId: 308 },
                { name: '新华大街', thirdId: 309 },
                { name: '运河大街', thirdId: 310 },
                { name: '玉桥', thirdId: 311 } ]
            },
            {
                name: '房山区',
                thirdData: [ { name: '长阳', thirdId: 312 },
                { name: '城关', thirdId: 313 },
                { name: '窦店', thirdId: 314 },
                { name: '房山城区', thirdId: 315 },
                { name: '韩村河', thirdId: 316 },
                { name: '良乡', thirdId: 317 },
                { name: '琉璃河', thirdId: 318 },
                { name: '十渡', thirdId: 319 },
                { name: '阎村', thirdId: 320 },
                { name: '燕山', thirdId: 321 },
                { name: '周口店', thirdId: 322 } ]
            },
            {
                name: '怀柔区',
                thirdData: [
                    { name: '怀柔城区', thirdId: 323 }
                ]
            },
            {
                name: '门头沟区',
                thirdData: [ { name: '滨河路', thirdId: 324 },
                { name: '城区', thirdId: 325 },
                { name: '城子', thirdId: 326 },
                { name: '东辛房', thirdId: 327 },
                { name: '军庄', thirdId: 328 },
                { name: '门头沟其他', thirdId: 329 },
                { name: '双峪', thirdId: 330 },
                { name: '新城', thirdId: 331 } ]
            },
            {
                name: '平谷区',
                thirdData: [ { name: '马昌营', thirdId: 332 },
                { name: '平谷城区', thirdId: 333 },
                { name: '平谷马坊', thirdId: 334 },
                { name: '夏各庄', thirdId: 335 } ]
            },
            {
                name: '密云县',
                thirdData: [ { name: '密云长城环岛', thirdId: 336 },
                { name: '密云城区', thirdId: 337 },
                { name: '密云其他', thirdId: 338 },
                { name: '密云水库', thirdId: 339 } ]
            },
            {
                name: '延庆县',
                thirdData: [ { name: '八达岭', thirdId: 340 },
                { name: '长城龙庆峡风景区', thirdId: 341 },
                { name: '大榆树', thirdId: 342 },
                { name: '康庄', thirdId: 343 },
                { name: '县城', thirdId: 344 },
                { name: '张山营', thirdId: 345 } ]
            },
            {
                name: '周边',
                thirdData: [ { name: '大厂', thirdId: 346 },
                { name: '固安', thirdId: 347 },
                { name: '廊坊', thirdId: 348 },
                { name: '其他', thirdId: 349 },
                { name: '十渡', thirdId: 350 },
                { name: '香河', thirdId: 351 },
                { name: '行宫', thirdId: 352 },
                { name: '燕郊', thirdId: 353 },
                { name: '涿州', thirdId: 354 } ]
            }
        ]
    },
    {
        name: '地铁',
        firstId: 1,
        secondData:[
            {
                name: '1号线',
                thirdData: [ { name: '苹果园站', thirdId: 355 },
                { name: '古城（石景山）站', thirdId: 356 },
                { name: '八角游乐园站', thirdId: 357 },
                { name: '八宝山站', thirdId: 358 },
                { name: '玉泉路站', thirdId: 359 },
                { name: '五棵松站', thirdId: 360 },
                { name: '万寿路站', thirdId: 361 },
                { name: '公主坟站', thirdId: 362 },
                { name: '军事博物馆站', thirdId: 363 },
                { name: '木樨地站', thirdId: 364 },
                { name: '南礼士路站', thirdId: 365 },
                { name: '复兴门站', thirdId: 366 },
                { name: '西单站', thirdId: 367 },
                { name: '天安门西站', thirdId: 368 },
                { name: '天安门东站', thirdId: 369 },
                { name: '王府井站', thirdId: 370 },
                { name: '东单站', thirdId: 371 },
                { name: '建国门站', thirdId: 372 },
                { name: '永安里站', thirdId: 373 },
                { name: '国贸站', thirdId: 374 },
                { name: '大望路站', thirdId: 375 },
                { name: '四惠站', thirdId: 376 },
                { name: '四惠东站', thirdId: 377 } ]
            },
            {
                name: '2号线',
                thirdData: [ { name: '鼓楼大街站', thirdId: 378 },
                { name: '安定门站', thirdId: 379 },
                { name: '雍和宫站', thirdId: 380 },
                { name: '东直门站', thirdId: 381 },
                { name: '东四十条站', thirdId: 382 },
                { name: '朝阳门站', thirdId: 383 },
                { name: '建国门站', thirdId: 384 },
                { name: '北京站', thirdId: 385 },
                { name: '崇文门站', thirdId: 386 },
                { name: '前门站', thirdId: 387 },
                { name: '和平门站', thirdId: 388 },
                { name: '宣武门站', thirdId: 389 },
                { name: '长椿街站', thirdId: 390 },
                { name: '复兴门站', thirdId: 391 },
                { name: '阜成门站', thirdId: 392 },
                { name: '车公庄站', thirdId: 393 },
                { name: '西直门站', thirdId: 394 },
                { name: '积水潭站', thirdId: 395 } ]
            },
            {
                name: '4号线',
                thirdData: [ { name: '安河桥北站', thirdId: 396 },
                { name: '北宫门站', thirdId: 397 },
                { name: '西苑站', thirdId: 398 },
                { name: '圆明园站', thirdId: 399 },
                { name: '北京大学东门站', thirdId: 400 },
                { name: '中关村站', thirdId: 401 },
                { name: '海淀黄庄站', thirdId: 402 },
                { name: '人民大学站', thirdId: 403 },
                { name: '魏公村站', thirdId: 404 },
                { name: '国家图书馆站', thirdId: 405 },
                { name: '动物园站', thirdId: 406 },
                { name: '西直门站', thirdId: 407 },
                { name: '新街口站', thirdId: 408 },
                { name: '平安里站', thirdId: 409 },
                { name: '西四站', thirdId: 410 },
                { name: '灵境胡同站', thirdId: 411 },
                { name: '西单站', thirdId: 412 },
                { name: '宣武门站', thirdId: 413 },
                { name: '菜市口站', thirdId: 414 },
                { name: '陶然亭站', thirdId: 415 },
                { name: '北京南站', thirdId: 416 },
                { name: '马家堡站', thirdId: 417 },
                { name: '角门西站', thirdId: 418 },
                { name: '公益西桥站', thirdId: 419 },
                { name: '新宫站', thirdId: 420 },
                { name: '西红门站', thirdId: 421 },
                { name: '高米店北站', thirdId: 422 },
                { name: '高米店南站', thirdId: 423 },
                { name: '枣园站', thirdId: 424 },
                { name: '清源路站', thirdId: 425 },
                { name: '黄村西大街站', thirdId: 426 },
                { name: '黄村火车站', thirdId: 427 },
                { name: '义和庄站', thirdId: 428 },
                { name: '生物医药基地站', thirdId: 429 },
                { name: '天宫院站', thirdId: 430 } ]
            },
            {
                name: '5号线',
                thirdData: [ { name: '天通苑北站', thirdId: 431 },
                { name: '天通苑站', thirdId: 432 },
                { name: '天通苑南站', thirdId: 433 },
                { name: '立水桥站', thirdId: 434 },
                { name: '立水桥南站', thirdId: 435 },
                { name: '北苑路北站', thirdId: 436 },
                { name: '大屯路东站', thirdId: 437 },
                { name: '惠新西街北口站', thirdId: 438 },
                { name: '惠新西街南口站', thirdId: 439 },
                { name: '和平西桥站', thirdId: 440 },
                { name: '和平里北街站', thirdId: 441 },
                { name: '雍和宫站', thirdId: 442 },
                { name: '北新桥站', thirdId: 443 },
                { name: '张自忠路站', thirdId: 444 },
                { name: '东四站', thirdId: 445 },
                { name: '灯市口站', thirdId: 446 },
                { name: '东单站', thirdId: 447 },
                { name: '崇文门站', thirdId: 448 },
                { name: '磁器口站', thirdId: 449 },
                { name: '天坛东门站', thirdId: 450 },
                { name: '蒲黄榆站', thirdId: 451 },
                { name: '刘家窑站', thirdId: 452 },
                { name: '宋家庄站', thirdId: 453 } ]
            },
            {
                name: '6号线',
                thirdData: [ { name: '海淀五路居站', thirdId: 454 },
                { name: '慈寿寺站', thirdId: 455 },
                { name: '花园桥站', thirdId: 456 },
                { name: '白石桥南站', thirdId: 457 },
                { name: '车公庄西站', thirdId: 458 },
                { name: '车公庄站', thirdId: 459 },
                { name: '平安里站', thirdId: 460 },
                { name: '北海北站', thirdId: 461 },
                { name: '南锣鼓巷站', thirdId: 462 },
                { name: '东四站', thirdId: 463 },
                { name: '朝阳门站', thirdId: 464 },
                { name: '东大桥站', thirdId: 465 },
                { name: '呼家楼站', thirdId: 466 },
                { name: '金台路站', thirdId: 467 },
                { name: '十里堡站', thirdId: 468 },
                { name: '青年路站', thirdId: 469 },
                { name: '褡裢坡站', thirdId: 470 },
                { name: '黄渠站', thirdId: 471 },
                { name: '常营站', thirdId: 472 },
                { name: '草房站', thirdId: 473 },
                { name: '物资学院路站', thirdId: 474 },
                { name: '通州北关站', thirdId: 475 },
                { name: '通运门站', thirdId: 476 },
                { name: '北运河西', thirdId: 477 },
                { name: '北运河东', thirdId: 478 },
                { name: '郝家府', thirdId: 479 },
                { name: '东夏园', thirdId: 480 },
                { name: '潞城', thirdId: 481 } ]
            },
            {
                name: '7号线',
                thirdData: [ { name: '北京西站', thirdId: 482 },
                { name: '湾子', thirdId: 483 },
                { name: '达官营', thirdId: 484 },
                { name: '广安门内', thirdId: 485 },
                { name: '菜市口', thirdId: 486 },
                { name: '虎坊桥', thirdId: 487 },
                { name: '珠市口', thirdId: 488 },
                { name: '桥湾', thirdId: 489 },
                { name: '磁器口', thirdId: 490 },
                { name: '广渠门内', thirdId: 491 },
                { name: '广渠门外', thirdId: 492 },
                { name: '双井', thirdId: 493 },
                { name: '九龙山', thirdId: 494 },
                { name: '大郊亭', thirdId: 495 },
                { name: '百子湾', thirdId: 496 },
                { name: '化工', thirdId: 497 },
                { name: '南楼梓庄', thirdId: 498 },
                { name: '欢乐谷景区', thirdId: 499 },
                { name: '垈头', thirdId: 500 },
                { name: '双合', thirdId: 501 },
                { name: '焦化厂', thirdId: 502 } ]
            },
            {
                name: '8号线',
                thirdData: [ { name: '南锣鼓巷站', thirdId: 503 },
                { name: '什刹海站', thirdId: 504 },
                { name: '鼓楼大街站', thirdId: 505 },
                { name: '安华桥站', thirdId: 506 },
                { name: '北土城站', thirdId: 507 },
                { name: '奥体中心站', thirdId: 508 },
                { name: '奥林匹克公园站', thirdId: 509 },
                { name: '森林公园南门站', thirdId: 510 },
                { name: '林萃桥站', thirdId: 511 },
                { name: '永泰庄站', thirdId: 512 },
                { name: '西小口站', thirdId: 513 },
                { name: '育新站', thirdId: 514 },
                { name: '霍营站', thirdId: 515 },
                { name: '回龙观东大街站', thirdId: 516 },
                { name: '平西府站', thirdId: 517 },
                { name: '育知路站', thirdId: 518 },
                { name: '朱辛庄站', thirdId: 519 } ]
            },
            {
                name: '9号线',
                thirdData: [ { name: '郭公庄站', thirdId: 520 },
                { name: '丰台科技园站', thirdId: 521 },
                { name: '科怡路站', thirdId: 522 },
                { name: '丰台南路站', thirdId: 523 },
                { name: '丰台东大街站', thirdId: 524 },
                { name: '七里庄站', thirdId: 525 },
                { name: '六里桥站', thirdId: 526 },
                { name: '六里桥东站', thirdId: 527 },
                { name: '北京西站', thirdId: 528 },
                { name: '军事博物馆站', thirdId: 529 },
                { name: '白堆子站', thirdId: 530 },
                { name: '白石桥南站', thirdId: 531 },
                { name: '国家图书馆站', thirdId: 532 } ]
            },
            {
                name: '10号线',
                thirdData: [ { name: '长春桥站', thirdId: 533 },
                { name: '火器营站', thirdId: 534 },
                { name: '巴沟站', thirdId: 535 },
                { name: '苏州街站', thirdId: 536 },
                { name: '海淀黄庄站', thirdId: 537 },
                { name: '知春里站', thirdId: 538 },
                { name: '知春路站', thirdId: 539 },
                { name: '西土城站', thirdId: 540 },
                { name: '牡丹园站', thirdId: 541 },
                { name: '健德门站', thirdId: 542 },
                { name: '北土城站', thirdId: 543 },
                { name: '安贞门站', thirdId: 544 },
                { name: '惠新西街南口站', thirdId: 545 },
                { name: '芍药居站', thirdId: 546 },
                { name: '太阳宫站', thirdId: 547 },
                { name: '三元桥站', thirdId: 548 },
                { name: '亮马桥站', thirdId: 549 },
                { name: '农业展览馆站', thirdId: 550 },
                { name: '团结湖站', thirdId: 551 },
                { name: '呼家楼站', thirdId: 552 },
                { name: '金台夕照站', thirdId: 553 },
                { name: '国贸站', thirdId: 554 },
                { name: '双井站', thirdId: 555 },
                { name: '劲松站', thirdId: 556 },
                { name: '潘家园站', thirdId: 557 },
                { name: '十里河站', thirdId: 558 },
                { name: '分钟寺站', thirdId: 559 },
                { name: '成寿寺站', thirdId: 560 },
                { name: '宋家庄站', thirdId: 561 },
                { name: '石榴庄站', thirdId: 562 },
                { name: '大红门站', thirdId: 563 },
                { name: '角门东站', thirdId: 564 },
                { name: '角门西站', thirdId: 565 },
                { name: '草桥站', thirdId: 566 },
                { name: '纪家庙站', thirdId: 567 },
                { name: '首经贸站', thirdId: 568 },
                { name: '丰台站', thirdId: 569 },
                { name: '泥洼站', thirdId: 570 },
                { name: '西局站', thirdId: 571 },
                { name: '六里桥站', thirdId: 572 },
                { name: '莲花桥站', thirdId: 573 },
                { name: '公主坟站', thirdId: 574 },
                { name: '西钓鱼台站', thirdId: 575 },
                { name: '慈寿寺站', thirdId: 576 },
                { name: '车道沟站', thirdId: 577 } ]
            },
            {
                name: '13号线',
                thirdData: [ { name: '西直门站', thirdId: 578 },
                { name: '大钟寺站', thirdId: 579 },
                { name: '知春路站', thirdId: 580 },
                { name: '五道口站', thirdId: 581 },
                { name: '上地站', thirdId: 582 },
                { name: '西二旗站', thirdId: 583 },
                { name: '龙泽站', thirdId: 584 },
                { name: '回龙观站', thirdId: 585 },
                { name: '霍营站', thirdId: 586 },
                { name: '立水桥站', thirdId: 587 },
                { name: '北苑站', thirdId: 588 },
                { name: '望京西站', thirdId: 589 },
                { name: '芍药居站', thirdId: 590 },
                { name: '光熙门站', thirdId: 591 },
                { name: '柳芳站', thirdId: 592 },
                { name: '东直门站', thirdId: 593 } ]
            },
            {
                name: '14号线',
                thirdData: [ { name: '张郭庄站', thirdId: 594 },
                { name: '园博园站', thirdId: 595 },
                { name: '大瓦窑站', thirdId: 596 },
                { name: '郭庄子站', thirdId: 597 },
                { name: '大井站', thirdId: 598 },
                { name: '七里庄站', thirdId: 599 },
                { name: '西局站', thirdId: 600 },
                { name: '北京南站站', thirdId: 601 },
                { name: '陶然桥站', thirdId: 602 },
                { name: '永定门外站', thirdId: 603 },
                { name: '景泰站', thirdId: 604 },
                { name: '蒲黄榆站', thirdId: 605 },
                { name: '方庄站', thirdId: 606 },
                { name: '十里河站', thirdId: 607 },
                { name: '北工大西门站', thirdId: 608 },
                { name: '平乐园', thirdId: 609 },
                { name: '九龙山站', thirdId: 610 },
                { name: '大望路站', thirdId: 611 },
                { name: '金台路站', thirdId: 612 },
                { name: '朝阳公园站', thirdId: 613 },
                { name: '枣营站', thirdId: 614 },
                { name: '东风北桥站', thirdId: 615 },
                { name: '将台站', thirdId: 616 },
                { name: '高家园', thirdId: 617 },
                { name: '望京南站', thirdId: 618 },
                { name: '阜通站', thirdId: 619 },
                { name: '望京站', thirdId: 620 },
                { name: '东湖渠站', thirdId: 621 },
                { name: '来广营站', thirdId: 622 },
                { name: '善各庄站', thirdId: 623 } ]
            },
            {
                name: '16号线',
                thirdData: [ { name: '北安河', thirdId: 624 },
                { name: '温阳路', thirdId: 625 },
                { name: '稻香湖路', thirdId: 626 },
                { name: '屯佃', thirdId: 627 },
                { name: '永丰', thirdId: 628 },
                { name: '永丰南', thirdId: 629 },
                { name: '西北旺', thirdId: 630 },
                { name: '马连洼', thirdId: 631 },
                { name: '农大南路', thirdId: 632 },
                { name: '西苑', thirdId: 633 } ]
            },
            {
                name: '机场快轨',
                thirdData: [ { name: '三号航站楼站', thirdId: 634 },
                { name: '二号航站楼站', thirdId: 635 },
                { name: '三元桥站', thirdId: 636 },
                { name: '东直门站', thirdId: 637 } ]
            },
            {
                name: '亦庄线',
                thirdData: [ { name: '宋家庄站', thirdId: 638 },
                { name: '肖村站', thirdId: 639 },
                { name: '小红门站', thirdId: 640 },
                { name: '旧宫站', thirdId: 641 },
                { name: '亦庄桥站', thirdId: 642 },
                { name: '亦庄文化园站', thirdId: 643 },
                { name: '万源街站', thirdId: 644 },
                { name: '荣京东街站', thirdId: 645 },
                { name: '荣昌东街站', thirdId: 646 },
                { name: '同济南路站', thirdId: 647 },
                { name: '经海路站', thirdId: 648 },
                { name: '次渠南站', thirdId: 649 },
                { name: '次渠站', thirdId: 650 } ]
            },
            {
                name: '昌平线',
                thirdData: [ { name: '西二旗站', thirdId: 651 },
                { name: '生命科学园站', thirdId: 652 },
                { name: '朱辛庄站', thirdId: 653 },
                { name: '巩华城站', thirdId: 654 },
                { name: '沙河站', thirdId: 655 },
                { name: '沙河高教园站', thirdId: 656 },
                { name: '南邵站', thirdId: 657 },
                { name: '北邵洼站', thirdId: 658 },
                { name: '昌平东关站', thirdId: 659 },
                { name: '昌平站', thirdId: 660 },
                { name: '十三陵景区站', thirdId: 661 },
                { name: '昌平西山口站', thirdId: 662 } ]
            },
            {
                name: '房山线',
                thirdData: [ { name: '苏庄站', thirdId: 663 },
                { name: '良乡南关站', thirdId: 664 },
                { name: '良乡大学城西站', thirdId: 665 },
                { name: '良乡大学城站', thirdId: 666 },
                { name: '良乡大学城北站', thirdId: 667 },
                { name: '广阳城站', thirdId: 668 },
                { name: '篱笆房站', thirdId: 669 },
                { name: '长阳站', thirdId: 670 },
                { name: '稻田站', thirdId: 671 },
                { name: '大葆台站', thirdId: 672 },
                { name: '郭公庄站', thirdId: 673 } ]
            },
            {
                name: '八通线',
                thirdData: [ { name: '四惠站', thirdId: 674 },
                { name: '四惠东站', thirdId: 675 },
                { name: '高碑店站', thirdId: 676 },
                { name: '传媒大学站', thirdId: 677 },
                { name: '双桥站', thirdId: 678 },
                { name: '管庄站', thirdId: 679 },
                { name: '八里桥站', thirdId: 680 },
                { name: '通州北苑站', thirdId: 681 },
                { name: '果园站', thirdId: 682 },
                { name: '九棵树站', thirdId: 683 },
                { name: '梨园站', thirdId: 684 },
                { name: '临河里站', thirdId: 685 },
                { name: '土桥站', thirdId: 686 } ]
            }
        ]
    },
    {
        name: '不限',
        firstId: 2,
        secondData:[
            {
                name: '不限',
                thirdData: [
                    {
                        name: '不限',
                        thirdId: -1
                    }
                ]
            }
        ]
    }
]
